# Fayl manzili: .github/workflows/aws.yml

name: Deploy to EC2 Server

on:
  push:
    branches:
      - main  # agar branchingiz boshqacha bo‘lsa, shu yerga yozing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub'dan kodni olish
        uses: actions/checkout@v2

      - name: Frontend va src fayllarni serverga yuborish
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "frontend/*,src/*"
          target: "/home/ubuntu/resabmittion"
          rm: true
